const fs = require("fs");
const nodemailer = require("nodemailer");

// "<Name> <Label> Resume.pdf" written by generate-pdf.js; used as the
// attachment filename so recipients see the current title.
function readDisplayName(fallback = "resume.pdf") {
  try {
    const name = fs.readFileSync("resume-name.txt", "utf8").trim();
    return name || fallback;
  } catch {
    return fallback;
  }
}

async function main() {
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_APP_PASSWORD;
  const recipient = process.env.RECIPIENT_EMAIL;
  const driveFileId = process.env.GDRIVE_FILE_ID;
  const filePath = process.env.EMAIL_ATTACHMENT_PATH || "resume.pdf";
  const displayName = readDisplayName();

  if (!user) throw new Error("SMTP_USER is required.");
  if (!pass) throw new Error("SMTP_APP_PASSWORD is required.");
  if (!recipient) throw new Error("RECIPIENT_EMAIL is required.");

  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: { user, pass },
  });

  const driveLink = driveFileId ? `https://drive.google.com/file/d/${driveFileId}/view` : null;
  const driveLine = driveLink ? `\n\nView or share the live version anytime: ${driveLink}` : "";
  const driveParagraph = driveLink
    ? `<p>View or share the live version anytime: <a href="${driveLink}">${driveLink}</a></p>`
    : "";

  await transporter.sendMail({
    from: `"DevResume Pipeline" <${user}>`,
    to: recipient,
    subject: "Your resume has just been updated",
    text: `Hi,\n\nYour resume has just been regenerated by the DevResume automation pipeline. The latest PDF is attached to this email.${driveLine}\n\n— DevResume Automation Pipeline`,
    html: `<p>Hi,</p><p>Your resume has just been regenerated by the DevResume automation pipeline. The latest PDF is attached to this email.</p>${driveParagraph}<p>&mdash; DevResume Automation Pipeline</p>`,
    attachments: [{ filename: displayName, path: filePath }],
  });

  console.log(`Sent ${displayName} to ${recipient}.`);
}

main().catch((error) => {
  console.error("send-email.js failed:", error);
  process.exit(1);
});
